# Generated by Django 5.2.3 on 2025-06-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('site_name', models.CharField(default='SlangSpot Latino', max_length=100)),
                ('video_explicativo_url', models.URLField(default='https://www.youtube.com/@aprendeconjhons', help_text='URL del video que explica qué es SlangSpot Latino', max_length=500)),
                ('video_explicativo_titulo', models.CharField(default='¿Qué es SlangSpot Latino?', help_text='Título del video explicativo', max_length=200)),
                ('video_explicativo_descripcion', models.TextField(default='Descubre qué es SlangSpot Latino y cómo te ayudará a aprender español latino de forma auténtica', help_text='Descripción del video explicativo')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuraciones del Sitio',
            },
        ),
    ]
