# Generated by Django 5.2.3 on 2025-06-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_video_explicativo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='video_explicativo_id',
            field=models.CharField(blank=True, default='rsjRSa_B1P0', help_text='ID del video de YouTube (ej: dQw4w9WgXcQ) para reproducir en la página', max_length=20),
        ),
    ]
