# Generated by Django 5.2.3 on 2025-07-01 01:54

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_lesson_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='Resumen corto del artículo', max_length=300)),
                ('category', models.CharField(choices=[('slang', 'Slang y Expresiones'), ('culture', 'Cultura'), ('tips', 'Tips de Aprendizaje'), ('stories', 'Historias y Anécdotas'), ('interviews', 'Entrevistas')], default='slang', max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/', validators=[core.validators.validate_file_size, core.validators.validate_image_extension])),
                ('is_published', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artículo del Blog',
                'verbose_name_plural': 'Artículos del Blog',
                'ordering': ['-created_at'],
            },
        ),
    ]
