# Generated by Django 5.2.3 on 2025-07-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Publicación del Foro', 'verbose_name_plural': 'Publicaciones del Foro'},
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('grammar', 'Gramática'), ('vocabulary', 'Vocabulario'), ('pronunciation', 'Pronunciación'), ('culture', 'Cultura'), ('questions', 'Preguntas'), ('resources', 'Recursos'), ('off-topic', 'Off Topic')], default='general', max_length=20),
        ),
    ]
