# Generated by Django 5.2.3 on 2025-07-02 03:12

from django.db import migrations

def fill_empty_text(apps, schema_editor):
    Expression = apps.get_model('core', 'Expression')
    for expr in Expression.objects.filter(text__isnull=True):
        expr.text = 'Sin texto'
        expr.save()
    for expr in Expression.objects.filter(text=''):
        expr.text = 'Sin texto'
        expr.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_forumpost_options_alter_forumpost_category'),
    ]

    operations = [
        migrations.RunPython(fill_empty_text),
    ]
