# Generated by Django 5.2.3 on 2025-07-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_temp_null_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
