# Generated by Django 5.2.3 on 2025-07-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fix_comment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='category',
            field=models.CharField(choices=[('slang', 'Jerga y Slang'), ('sayings', 'Dichos Populares'), ('expressions', 'Expresiones Coloquiales'), ('idioms', 'Modismos')], default='grammar', max_length=20),
        ),
    ]
